apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    # Do not push the image to Docker Hub
    push: false
  artifacts:
    - image: stephengrider/multi-client
      # Refer to client folder
      context: client
      docker:
        # Use Dockerfile.dev inside client folder for local development
        dockerfile: Dockerfile.dev
      sync:
        # Anytime there is a change in a js, html and css file, put it in the container
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: stephengrider/multi-server
      context: server
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: stephengrider/multi-worker
      context: worker
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml        
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
